export const INITIAL_HOMEPAGE_BLUEPRINT = [
  {
    key: "hero",
    type: "hero_slider",
    title: "Dressed in Quiet Luxury",
    subtitle: "Handcrafted unstitched fabrics. Refined textures. Elegance that whispers rather than shouts.",
    cta_text: "Explore Unstitched Fabrics",
    cta_link: "/categories/women",
    rank: 0,
    is_active: true,
    settings: null,
  },
  {
    key: "departments",
    type: "cards_grid",
    title: "Shop by Department",
    subtitle: "Explore collections for Women, Men, and Kids",
    cta_text: null,
    cta_link: null,
    rank: 1,
    is_active: true,
    settings: {
      cards: [
        {
          id: "dept_women",
          title: "Shop Women",
          subtitle: "Unstitched & Luxury Lawn",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
          link: "/categories/women",
        },
        {
          id: "dept_men",
          title: "Shop Men",
          subtitle: "Pure Boski & Cotton",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
          link: "/categories/men",
        },
        {
          id: "dept_kids",
          title: "Shop Kids",
          subtitle: "Junior Festive Cuts",
          image_url: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80",
          link: "/categories/children",
        },
      ],
    },
  },
  {
    key: "featured_brands",
    type: "cards_grid",
    title: "Featured Brands",
    subtitle: "Explore Pakistan's favourite labels, all in one place.",
    cta_text: null,
    cta_link: null,
    rank: 2,
    is_active: true,
    settings: {
      cards: [
        { id: "brand_khaadi", title: "Khaadi", subtitle: "Explore collection", image_url: "/images/brands/khaadi.svg", link: "/brands/khaadi" },
        { id: "brand_sapphire", title: "Sapphire", subtitle: "Explore collection", image_url: "/images/brands/sapphire.svg", link: "/brands/sapphire" },
        { id: "brand_gul_ahmed", title: "Gul Ahmed", subtitle: "Explore collection", image_url: "/images/brands/gul-ahmed.svg", link: "/brands/gul-ahmed" },
        { id: "brand_j", title: "J.", subtitle: "Explore collection", image_url: "/images/brands/j.svg", link: "/brands/j-dot" },
        { id: "brand_alkaram", title: "Alkaram", subtitle: "Explore collection", image_url: "/images/brands/alkaram.png", link: "/brands/alkaram" },
        { id: "brand_limelight", title: "Limelight", subtitle: "Explore collection", image_url: "/images/brands/limelight.svg", link: "/brands/limelight" },
      ],
    },
  },
  {
    key: "new_arrivals",
    type: "product_carousel",
    title: "New Arrivals",
    subtitle: "Hand-selected unstitched fabrics and newest seasonal cuts",
    cta_text: "View All New Arrivals",
    cta_link: "/store?sortBy=newest",
    rank: 3,
    is_active: true,
    settings: {
      product_ids: [],
    },
  },
  {
    key: "best_sellers",
    type: "product_carousel",
    title: "Best Sellers",
    subtitle: "Customer favourite unstitched fabrics across Pakistan",
    cta_text: "View All Best Sellers",
    cta_link: "/store?sortBy=best-selling",
    rank: 4,
    is_active: true,
    settings: {
      product_ids: [],
    },
  },
  {
    key: "journal",
    type: "lookbook",
    title: "The NAQSH Journal",
    subtitle: "Stories & Style • Fabric narratives and heritage crafts",
    cta_text: "Read the blog",
    cta_link: "/blog",
    rank: 7,
    is_active: true,
    settings: {
      cards: [
        {
          id: "journal_1",
          title: "The art of luxury lawn",
          subtitle: "A closer look at the fabrics behind your favourite summer pieces.",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
          link: "/blog#art-of-pakistani-lawn",
        },
        {
          id: "journal_2",
          title: "Celebrating embroidery",
          subtitle: "Discover the detail and heritage of zardozi and tilla.",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
          link: "/blog#reviving-zardozi-and-tilla",
        },
        {
          id: "journal_3",
          title: "Everyday, beautifully styled",
          subtitle: "Find inspiration in timeless colours and effortless matching sets.",
          image_url: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80",
          link: "/blog#modern-monochrome-unstitched",
        },
      ],
    },
  },
  {
    key: "features",
    type: "features_strip",
    title: "Our Guarantees",
    subtitle: "The NAQSH 100% Unstitched Fabric experience",
    cta_text: null,
    cta_link: null,
    rank: 8,
    is_active: true,
    settings: null,
  },
  {
    key: "featured_categories",
    type: "featured_categories",
    title: "Find Your Perfect Unstitched Cut",
    subtitle: "Explore 100% pure unstitched fabrics: Ladies luxury lawn, pure silks, and Gents heirloom Boski cuts",
    cta_text: null,
    cta_link: null,
    rank: 2,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_ladies_3pc",
          title: "Ladies 3-Piece Luxury",
          subtitle: "1,250+ Fabric Cuts",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85",
          link: "/categories/3pc",
          badge: "LUXURY LAWN",
        },
        {
          id: "card_ladies_2pc",
          title: "Ladies 2-Piece Printed",
          subtitle: "950+ Fabric Cuts",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=85",
          link: "/categories/2pc",
          badge: "BESTSELLER",
        },
        {
          id: "card_silks",
          title: "Pure Silk & Chiffon",
          subtitle: "Festive Unstitched",
          image_url: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=85",
          link: "/categories/silk",
          badge: "EXCLUSIVE",
        },
        {
          id: "card_gents_boski",
          title: "Men's Pure Boski",
          subtitle: "Heirloom Silk 4.5m Cuts",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=85",
          link: "/categories/boski",
          badge: "PREMIUM SILK",
        },
        {
          id: "card_gents_cotton",
          title: "Men's Wash & Wear",
          subtitle: "1,000+ Fabric Cuts",
          image_url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=85",
          link: "/categories/wash-wear",
          badge: "SUMMER EDITS",
        },
        {
          id: "card_children",
          title: "Children Unstitched",
          subtitle: "Junior Festive Cuts",
          image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=85",
          link: "/categories/children",
          badge: "JUNIOR FABRICS",
        },
      ],
    },
  },
  {
    key: "sale_banner",
    type: "sale_banner",
    title: "Flat 20% Off Luxury Unstitched Fabrics & Seasonal Cuts",
    subtitle: "Hand-embroidered lawn, pure silk dupattas, and Gents heirloom boski suit cuts. Applicable at checkout.",
    cta_text: "Shop Unstitched Sale →",
    cta_link: "/categories/sale",
    rank: 3,
    is_active: true,
    settings: {
      badge: "LIMITED TIME FESTIVE GALA",
      promo_code: "LUXE20",
      hours: 5,
      minutes: 41,
      seconds: 12,
    },
  },
  {
    key: "curated_tabs",
    type: "product_carousel",
    title: "Curated Unstitched Cuts for You",
    subtitle: "Hand-selected unstitched fabrics from our latest seasonal designer collections",
    cta_text: "View All Unstitched Cuts →",
    cta_link: "/categories/women",
    rank: 4,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_crimson",
          title: "Royal Crimson Embroidered Lawn 3-Piece",
          subtitle: "LADIES UNSTITCHED",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
          price: 6950,
          original_price: 8688,
          discount_percent: 20,
          badge: "SALE",
          link: "/categories/3pc",
        },
        {
          id: "card_organza",
          title: "Ivory Pearl Organza Formal Ensemble Cut",
          subtitle: "FESTIVE UNSTITCHED",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
          price: 18500,
          original_price: 26428,
          discount_percent: 30,
          badge: "SALE",
          link: "/categories/silk",
        },
        {
          id: "card_silk_print",
          title: "Printed Silk Unstitched Suit - Midnight Mirage",
          subtitle: "2-PIECE UNSTITCHED",
          image_url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
          price: 8200,
          original_price: 11714,
          discount_percent: 30,
          badge: "SALE",
          link: "/categories/2pc",
        },
        {
          id: "card_boski_suit",
          title: "Pure Heirloom Silk Boski Unstitched Cut 4.5m",
          subtitle: "GENTS HEIRLOOM",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
          price: 14500,
          original_price: 18125,
          discount_percent: 20,
          badge: "SALE",
          link: "/categories/boski",
        },
        {
          id: "card_egyptian_cotton",
          title: "Egyptian Combed Cotton Wash & Wear Cut 4.5m",
          subtitle: "GENTS UNSTITCHED",
          image_url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80",
          price: 5200,
          original_price: 6500,
          discount_percent: 20,
          badge: "SALE",
          link: "/categories/wash-wear",
        },
      ],
    },
  },
  {
    key: "promo_banners",
    type: "promo_banner",
    title: "Seasonal Spotlights",
    subtitle: "Exclusive limited drops",
    rank: 5,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_lawn_spotlight",
          title: "Summer Unstitched Lawn Edit",
          subtitle: "Curated Pakistani Couture",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85",
          badge: "LIMITED EDITION",
          link: "/categories/women",
        },
        {
          id: "card_pret_spotlight",
          title: "Festive Chiffon & Organza Edit",
          subtitle: "Handcrafted Unstitched Coutures",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=85",
          badge: "NEW ARRIVALS",
          link: "/categories/women",
        },
      ],
    },
  },
  {
    key: "customer_reviews",
    type: "customer_reviews",
    title: "Loved by Thousands",
    subtitle: "Real feedback from verified shoppers across Pakistan who trust NAQSH for unstitched fabric cuts.",
    rank: 6,
    is_active: true,
    settings: null,
  },
  {
    key: "fabric_strip",
    type: "fabric_strip",
    title: "Curated Seasonal Categories",
    subtitle: "Explore pure Pima lawn, artisanal formals, and handloom unstitched fabrics for modern celebrations.",
    rank: 7,
    is_active: true,
    settings: {
      cards: [
        {
          id: "circle_1",
          title: "3-Piece Luxury Lawn",
          subtitle: "Embroidered Voile & Chiffon",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=85",
          badge: "TRENDING",
          link: "/categories/3pc",
        },
        {
          id: "circle_2",
          title: "Unstitched 2-Piece",
          subtitle: "Printed & Jacquard Lawn",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=85",
          badge: "BESTSELLER",
          link: "/categories/2pc",
        },
        {
          id: "circle_3",
          title: "Unstitched 1-Piece Cuts",
          subtitle: "Embroidered Lawn & Cambric",
          image_url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=85",
          badge: "NEW IN",
          link: "/categories/women",
        },
        {
          id: "circle_4",
          title: "Luxury Chiffon & Silk",
          subtitle: "Festive Embroidered Couture",
          image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=85",
          badge: "HOT",
          link: "/categories/silk",
        },
        {
          id: "circle_5",
          title: "Handloom Pashmina",
          subtitle: "Pure Cashmere & Wool Wraps",
          image_url: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=600&q=85",
          badge: "HERITAGE",
          link: "/categories/women",
        },
        {
          id: "circle_6",
          title: "Men's Unstitched Boski",
          subtitle: "Pure Heirloom Silk 4.5m Cuts",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=85",
          badge: "CLASSIC",
          link: "/categories/boski",
        },
        {
          id: "circle_7",
          title: "Men's Wash & Wear",
          subtitle: "Fine Egyptian Cotton Suit Cuts",
          image_url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=85",
          badge: "POPULAR",
          link: "/categories/wash-wear",
        },
        {
          id: "circle_8",
          title: "Junior Unstitched Cuts",
          subtitle: "Festive Kids Fabric Lengths",
          image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=85",
          badge: "JUNIOR",
          link: "/categories/children",
        },
      ],
    },
  },
  {
    key: "instagram_feed",
    type: "instagram_feed",
    title: "Live on Instagram",
    subtitle: "Behind the looms, artisanal hand-embroidery, and seasonal luxury unstitched fabric stories.",
    rank: 8,
    is_active: false,
    settings: {
      profile_url: "https://www.instagram.com/itx_shk_selfish/",
      username: "@itx_shk_selfish",
      cards: [
        {
          id: "itx_reel_1",
          image_url: "/images/reels/itx_reel_1.jpg",
          video_url: "/videos/reels/reel1.mp4",
          title: "\"you can't always get what you want\" • @itx_shk_selfish",
          views: "54.8K",
          likes: "4.2k",
          comments: "189",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_2",
          image_url: "/images/reels/itx_reel_2.jpg",
          video_url: "/videos/reels/reel2.mp4",
          title: "\"PASTA\" vibes • @itx_shk_selfish",
          views: "67.5K",
          likes: "5.4k",
          comments: "256",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_3",
          image_url: "/images/reels/itx_reel_3.jpg",
          video_url: "/videos/reels/reel3.mp4",
          title: "Aaj tak aise dost nhi bane jo... • @itx_shk_selfish",
          views: "41.2K",
          likes: "3.1k",
          comments: "142",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_4",
          image_url: "/images/reels/itx_reel_4.jpg",
          video_url: "/videos/reels/reel4.mp4",
          title: "Socha tha Bade ho kar Zindagi Aasan Hogi... • @itx_shk_selfish",
          views: "38.9K",
          likes: "2.9k",
          comments: "118",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
      ],
    },
  },
  {
    key: "newsletter",
    type: "newsletter",
    title: "Get First Access to New Drops",
    subtitle: "Subscribe for exclusive early access, fabric swatch lookbooks, and members-only unstitched offers.",
    rank: 9,
    is_active: true,
    settings: null,
  },
]
