export const INITIAL_HOMEPAGE_BLUEPRINT = [
  {
    key: "hero",
    type: "hero_slider",
    title: "Dressed in Quiet Luxury",
    subtitle: "Handcrafted fabrics. Refined silhouettes. Elegance that whispers rather than shouts.",
    cta_text: "Explore Collection",
    cta_link: "/store",
    rank: 0,
    is_active: true,
    settings: null,
  },
  {
    key: "features",
    type: "features_strip",
    title: "Our Guarantees",
    subtitle: "The NAQSH shopping experience",
    cta_text: null,
    cta_link: null,
    rank: 1,
    is_active: true,
    settings: null,
  },
  {
    key: "featured_categories",
    type: "featured_categories",
    title: "Find Your Perfect Style",
    subtitle: "From unstitched luxury fabrics to ready-to-wear kurtas",
    cta_text: null,
    cta_link: null,
    rank: 2,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_unstitched",
          title: "Unstitched",
          subtitle: "240+ Fabrics",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=unstitched",
          badge: "LUXURY LAWN",
        },
        {
          id: "card_pret",
          title: "Ready to Wear",
          subtitle: "180+ Styles",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=women",
          badge: "TRENDING",
        },
        {
          id: "card_coords",
          title: "Co-ords",
          subtitle: "110+ Sets",
          image_url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=co-ords",
          badge: "POPULAR",
        },
        {
          id: "card_footwear",
          title: "Footwear",
          subtitle: "120+ Pairs",
          image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=footwear",
          badge: "KHUSSA & HEELS",
        },
        {
          id: "card_bags",
          title: "Bags",
          subtitle: "90+ Designs",
          image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=bags",
          badge: "LEATHER",
        },
        {
          id: "card_accessories",
          title: "Accessories",
          subtitle: "200+ Items",
          image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=accessories",
          badge: "JEWELLERY",
        },
        {
          id: "card_men",
          title: "Men",
          subtitle: "60+ Styles",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=85",
          link: "/store?category=men",
          badge: "FESTIVE",
        },
      ],
    },
  },
  {
    key: "sale_banner",
    type: "sale_banner",
    title: "Flat 20% Off Ready-to-Wear & Luxury Pret",
    subtitle: "Hand-spun pashmina wraps, pure chiffon dupattas, and intricate zari embroideries. Applicable at checkout.",
    cta_text: "Shop The Gala →",
    cta_link: "/store",
    rank: 3,
    is_active: true,
    settings: {
      badge: "LIMITED TIME FESTIVE GALA",
      promo_code: "LUXE20",
      hours: 5,
      minutes: 41,
      seconds: 12,
    },
  },
  {
    key: "curated_tabs",
    type: "product_carousel",
    title: "Curated for You",
    subtitle: "Hand-selected pieces from our latest designer collections",
    cta_text: "View All Products →",
    cta_link: "/store",
    rank: 4,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_sweatshirt",
          title: "Medusa Sweatshirt",
          subtitle: "SWEATSHIRTS",
          image_url: "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png",
          price: 2800,
          original_price: 3600,
          discount_percent: 22,
          badge: "SALE",
          link: "/products/sweatshirt",
        },
        {
          id: "card_sweatpants",
          title: "Medusa Sweatpants",
          subtitle: "PANTS",
          image_url: "https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png",
          price: 2800,
          original_price: 4242,
          discount_percent: 34,
          badge: "SALE",
          link: "/products/sweatpants",
        },
        {
          id: "card_tshirt",
          title: "Medusa T-Shirt",
          subtitle: "SHIRTS",
          image_url: "https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png",
          price: 2800,
          original_price: 3500,
          discount_percent: 20,
          badge: "SALE",
          link: "/products/t-shirt",
        },
        {
          id: "card_shorts",
          title: "Medusa Shorts",
          subtitle: "MERCH",
          image_url: "https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png",
          price: 2800,
          original_price: 3500,
          discount_percent: 20,
          badge: "SALE",
          link: "/products/shorts",
        },
        {
          id: "card_crimson",
          title: "Royal Crimson Embroidered Lawn 3-Piece",
          subtitle: "UNSTITCHED FABRIC",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
          price: 6950,
          original_price: 8688,
          discount_percent: 20,
          badge: "SALE",
          link: "/products/royal-crimson-embroidered-lawn-3pc",
        },
        {
          id: "card_organza",
          title: "Ivory Pearl Organza Formal Ensemble",
          subtitle: "FESTIVE FORMALS",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
          price: 18500,
          original_price: 26428,
          discount_percent: 30,
          badge: "SALE",
          link: "/products/ivory-pearl-organza-formal-ensemble",
        },
        {
          id: "card_silk_coord",
          title: "Printed Silk Co-ord Set - Midnight Mirage",
          subtitle: "CO-ORDS SETS",
          image_url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
          price: 8200,
          original_price: 11714,
          discount_percent: 30,
          badge: "SALE",
          link: "/products/printed-silk-coord-set-midnight",
        },
        {
          id: "card_sage_kurta",
          title: "Sage Green Embroidered Pret Kurta",
          subtitle: "READY TO WEAR",
          image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
          price: 4450,
          original_price: 5705,
          discount_percent: 22,
          badge: "SALE",
          link: "/products/sage-green-embroidered-pret-kurta",
        },
      ],
    },
  },
  {
    key: "promo_banners",
    type: "promo_banner",
    title: "Seasonal Spotlights",
    subtitle: "Exclusive limited drops",
    rank: 5,
    is_active: true,
    settings: {
      cards: [
        {
          id: "card_lawn_spotlight",
          title: "Summer Unstitched Lawn Edit",
          subtitle: "Curated Pakistani Couture",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85",
          badge: "LIMITED EDITION",
          link: "/store?category=unstitched",
        },
        {
          id: "card_pret_spotlight",
          title: "Contemporary Pret & Co-ords",
          subtitle: "Designed for Celebrations",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=85",
          badge: "NEW ARRIVALS",
          link: "/store?category=women",
        },
      ],
    },
  },
  {
    key: "customer_reviews",
    type: "customer_reviews",
    title: "Loved by Thousands",
    subtitle: "Real feedback from verified shoppers across Pakistan who trust NAQSH for celebratory moments.",
    rank: 6,
    is_active: true,
    settings: null,
  },
  {
    key: "fabric_strip",
    type: "fabric_strip",
    title: "Curated Seasonal Categories",
    subtitle: "Explore pure Pima lawn, artisanal formals, and handloom wraps tailored for modern celebrations.",
    rank: 7,
    is_active: true,
    settings: {
      cards: [
        {
          id: "circle_1",
          title: "3-Piece Luxury Lawn",
          subtitle: "Embroidered Voile & Chiffon",
          image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=85",
          badge: "TRENDING",
          link: "/store?category=women",
        },
        {
          id: "circle_2",
          title: "Unstitched 2-Piece",
          subtitle: "Printed & Jacquard Lawn",
          image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=85",
          badge: "BESTSELLER",
          link: "/store?category=unstitched",
        },
        {
          id: "circle_3",
          title: "Ready to Wear Pret",
          subtitle: "Tailored Kurtas & Co-ords",
          image_url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=85",
          badge: "NEW IN",
          link: "/store?category=women",
        },
        {
          id: "circle_4",
          title: "Luxury Chiffon & Silk",
          subtitle: "Festive Embroidered Couture",
          image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=85",
          badge: "HOT",
          link: "/store?category=luxury",
        },
        {
          id: "circle_5",
          title: "Handloom Pashmina",
          subtitle: "Pure Cashmere & Wool Wraps",
          image_url: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=600&q=85",
          badge: "HERITAGE",
          link: "/store?category=luxury",
        },
        {
          id: "circle_6",
          title: "Men's Festive Kurta",
          subtitle: "Jacquard Silk & Fine Cotton",
          image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=85",
          badge: "CLASSIC",
          link: "/store?category=men",
        },
      ],
    },
  },
  {
    key: "instagram_feed",
    type: "instagram_feed",
    title: "Live on Instagram",
    subtitle: "Behind the seams, bespoke bridal fittings, and seasonal luxury pret stories.",
    rank: 8,
    is_active: true,
    settings: {
      profile_url: "https://www.instagram.com/itx_shk_selfish/",
      username: "@itx_shk_selfish",
      cards: [
        {
          id: "itx_reel_1",
          image_url: "/images/reels/itx_reel_1.jpg",
          video_url: "/videos/reels/reel1.mp4",
          title: "\"you can't always get what you want\" • @itx_shk_selfish",
          views: "54.8K",
          likes: "4.2k",
          comments: "189",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_2",
          image_url: "/images/reels/itx_reel_2.jpg",
          video_url: "/videos/reels/reel2.mp4",
          title: "\"PASTA\" vibes • @itx_shk_selfish",
          views: "67.5K",
          likes: "5.4k",
          comments: "256",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_3",
          image_url: "/images/reels/itx_reel_3.jpg",
          video_url: "/videos/reels/reel3.mp4",
          title: "Aaj tak aise dost nhi bane jo... • @itx_shk_selfish",
          views: "41.2K",
          likes: "3.1k",
          comments: "142",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
        {
          id: "itx_reel_4",
          image_url: "/images/reels/itx_reel_4.jpg",
          video_url: "/videos/reels/reel4.mp4",
          title: "Socha tha Bade ho kar Zindagi Aasan Hogi... • @itx_shk_selfish",
          views: "38.9K",
          likes: "2.9k",
          comments: "118",
          link: "https://www.instagram.com/itx_shk_selfish/",
        },
      ],
    },
  },
  {
    key: "newsletter",
    type: "newsletter",
    title: "Get First Access to New Drops",
    subtitle: "Subscribe for exclusive early access, styling lookbooks, and members-only offers.",
    rank: 9,
    is_active: true,
    settings: null,
  },
]
